// <auto-generated />
using System;
using EvaluatingApp.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvaluatingApp.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20200630105857_CreateWebPerformanceDb")]
    partial class CreateWebPerformanceDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EvaluatingApp.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EvaluatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ResponseTime")
                        .HasColumnType("float");

                    b.Property<int>("UrlAddressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrlAddressId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("EvaluatingApp.Models.UrlAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("urlAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UrlAdresses");
                });

            modelBuilder.Entity("EvaluatingApp.Models.Response", b =>
                {
                    b.HasOne("EvaluatingApp.Models.UrlAddress", "Url")
                        .WithMany("ResponsesList")
                        .HasForeignKey("UrlAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
